### ISSUE TITLE
Find someone who wants to host this list

### ISSUE THREAD

**Issue by JohnLockwood** [CodeSolid/tech_coops_growing#3]
Hi.

This list needs a new owner.  If you want it let me know.  Thanks!

**Comment by rmharrison** [comment]
Any update on a new owner and/or status of the project?

**Comment by JohnLockwood** [comment]
@rmharrison - Wow, four years later I reply.  Well, clearly I've checked out on this one.  If you're still interested and wanted to pull the repo and push to a new repo, let me know and I'll shut this one down.

**Comment by JohnLockwood** [comment]
@rmharrison - with that it's yours if you want it.  Closing the issue though.  Thanks!
